### ISSUE TITLE
Left click to open the context menu

### ISSUE THREAD

**Issue by nohajc** [iovxw/ksni#19]
How can I make left click open the menu the same as right click? I assume it means implementing the correct `activate` action although it is not clear to me what exactly to call there.

**Comment by iovxw** [comment]
There is an `org.freedesktop.StatusNotifierItem.ItemIsMenu`

> BOOL: The item only support the context menu, the visualization should prefer showing the menu or sending ContextMenu() instead of Activate()

But nobody uses it, not even KDE
https://github.com/KDE/kstatusnotifieritem/blob/f03e80da107c80d28662995ad2b9f1214902b3fa/src/kstatusnotifieritemdbus_p.cpp#L161

GNOME uses an unstandardized approach that seems incompatible with other implementations
https://github.com/ubuntu/gnome-shell-extension-appindicator/blob/e365c01682bc77e31c10b82fe9169817215838b3/appIndicator.js#L780

So this may not be possible at the moment

**Comment by nohajc** [comment]
Well, it actually works if I use this go library:

https://github.com/fyne-io/systray

I haven't figured out yet how they do it though...

**Comment by iovxw** [comment]
> Well, it actually works if I use this go library:
> 
> https://github.com/fyne-io/systray
> 
> I haven't figured out yet how they do it though...

It uses the `ItemIsMenu`

What desktop environment (and the tray plugin, if any) are you using?

**Comment by nohajc** [comment]
I tested with Fedora 39 KDE and the left click worked which is really interesting given what you said.

**Comment by nohajc** [comment]
I also forked your repo and tried this yesterday but the change had no effect:
https://github.com/nohajc/ksni/commit/314027c0a4fe9d4023702f95d4657ccfafd21c75

**Comment by wusyong** [comment]
Hey sorry if my question is irrelevant. But could this crate being used as a context menu or popup menu?
I mean the menu when people right click in the window.
Or is there any other freedesktop spec I should look for?

**Comment by iovxw** [comment]
Done, see https://docs.rs/ksni/0.3/ksni/trait.Tray.html#associatedconstant.MENU_ON_ACTIVATE and https://github.com/iovxw/ksni/blob/e5f2bb1be12a7b9cb5ff8d87712f17111472f381/src/dbus_interface.rs#L66-L78

**Comment by iovxw** [comment]
> Hey sorry if my question is irrelevant. But could this crate being used as a context menu or popup menu?
> I mean the menu when people right click in the window.

The DBusMenu can be used [for a global menu](https://github.com/KDE/plasma-workspace/blob/master/appmenu/com.canonical.AppMenu.Registrar.xml), but not context menu

> Or is there any other freedesktop spec I should look for?

Maybe https://wayland-book.com/xdg-shell-in-depth/popups.html

**Comment by wusyong** [comment]
@iovxw  Thanks for the reply! Those are what I found as well. I think I'll choose wayland's popup surface.
Winit devs also plan to support it in next minor version.
