### ISSUE TITLE
Use `svg` for icon.

### ISSUE THREAD

**Issue by TornaxO7** [iovxw/ksni#20]
Hello! It would be cool if you are allowed to use a `svg` icon for the system tray. Currently it only allows it [in ARGB32](https://docs.rs/ksni/0.2.1/ksni/struct.Icon.html).

**Comment by TornaxO7** [comment]
[Welp](https://www.freedesktop.org/wiki/Specifications/StatusNotifierItem/Icons/)

> The data is represented in ARGB32 format and is in the network byte order, to make easy the communication over the network between little and big endian machines.

**Comment by nozwock** [comment]
I think it works if the svg is in the proper symbolic folder and the name is used with `ksni::Tray::icon_name()`
