### ISSUE TITLE
custom dbus name for StatusNotifierWatcher

### ISSUE THREAD

**Issue by mokurin000** [iovxw/ksni#24]
This is for flatpak packaging. If we own `org.kde.StatusNotifierItem-2-1`, it will be tricky: it's not guaranteed that my app will have PID 2.
As [workarounds from chromium](https://chromium-review.googlesource.com/c/chromium/src/+/4179380), instead we register a existing dbus name we are using, and everything works fine.
> To address this, just use the default bus name we were given on
> initially connecting to the bus.  This violates the spec, but there's
> actually no consequence for doing this.

**Comment by eminfedar** [comment]
I have problems with flatpak too and probably related to this.

I don't have any problem when I add `"--socket=session-bus"` to finish-args. But flathub doesn't like "I can talk anything" permission.

When I removed "--socket=session-bus" and only `"--talk-name=org.kde.StatusNotifierWatcher"` left, I got `D-Bus error: org.freedesktop.DBus.Error.ServiceUnknown (org.freedesktop.DBus.Error.ServiceUnknown)`

**Comment by mokurin000** [comment]
> I have problems with flatpak too and probably related to this.
> 
> I don't have any problem when I add `"--socket=session-bus"` to finish-args. But flathub doesn't like "I can talk anything" permission.
> 
> When I removed "--socket=session-bus" and only `"--talk-name=org.kde.StatusNotifierWatcher"` left, I got `D-Bus error: org.freedesktop.DBus.Error.ServiceUnknown (org.freedesktop.DBus.Error.ServiceUnknown)`

did you try https://github.com/waylyrics/ksni/tree/feat-custom-dbus-name

**Comment by eminfedar** [comment]
0.2.2 update and run_without_dbus_name() solved my problem.
