### ISSUE TITLE
Rendering different menu during runtime.

### ISSUE THREAD

**Issue by emirror-de** [iovxw/ksni#9]
I changed the provided example to [this one](https://github.com/emirror-de/ksni/blob/8b0268ab8d0dae57df4840549793f81cec4f95be/examples/example.rs#L18).
However, the menu does not get updated. When clicking on a StandardItem it panics with the following error:

```rust
thread '<unnamed>' panicked at 'index out of bounds: the len is 2 but the index is 3', /home/projects/ksni/src/service.rs:702:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Is it possible to update the menu during runtime?

**Comment by iovxw** [comment]
Fixed! Thank you for the report!
